stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - docker compose build

test-job:
  stage: test
  script:
    - echo "Запущен тест"
    - docker compose up 
    - echo "Контейнер запущен"
    - docker compose down
    - echo "Контейнер удален"

deploy-job:
  stage: deploy
  script:
    - docker compose up -d 
  