stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - docker build -t backend-image .

test-job:
  stage: test
  script:
    - echo "Тестирование прошло успешно"

deploy-job:
  stage: deploy
  script:
    - docker compose up -d 
  