stages:
  - build
  - test
  - deploy

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

before_script:
  - docker info

build:
  stage: build
  script:
    - echo "Создание контейнера..."
    - docker compose build

test:
  stage: test
  script:
    - echo "Запуск теста..."
    - docker compose up -d
    - docker compose down

deploy:
  stage: deploy
  script:
    - echo "Деплой приложения..."

