stages:
  - build
  - test
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  COMPOSE_PROJECT_NAME: my_app

services:
  - docker:dind

build:
  stage: build
  script:
    - echo "Создание контейнера..."
    - docker compose build

test:
  stage: test
  script:
    - echo "Запуск теста..."
    - docker compose up -d
    - docker compose down

deploy:
  stage: deploy
  script:
    - echo "Деплой приложения..."

