services:
  db:
    image: postgres:13
    container_name: freelance_bot_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - freelance_network

  web:
    build: .
    container_name: freelance_bot_web
    environment:
      TOKEN: ${TOKEN}
      URL_ALCHEMY: ${URL_ALCHEMY}
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - freelance_network

volumes:
  db_data:

networks:
  freelance_network:
    driver: bridge
